### ISSUE TITLE
Some Questions about the training code

### ISSUE THREAD

**Issue by MikeDean2367** [ContextualAI/gritlm#10]
Firstly, I want to commend you on the exceptional work you've published and for making the repository available. It's been enlightening reviewing your code, and I have a few questions that I hope you could help clarify, particularly about the training code:

1. As we can see, the GradCache technique is used for `GradCacheTrainer`. In the [code](https://github.com/ContextualAI/gritlm/blob/main/gritlm/training/gradcache_trainer.py#L584), there are six conditions including `self.split_emb`, `self.split_emb_full` and so on. I'm curious to understand whether the `else` clause is the only instance where GradCacheTrainer is utilized in the training process.
2. When using the GradCacheTrainer, is it necessary to define the `training_step` function as outlined in the [here](https://github.com/ContextualAI/gritlm/blob/main/gritlm/training/run.py#L385), or can this be omitted?

My answer to these questions is `yes` for both.

**Comment by Muennighoff** [comment]
> Firstly, I want to commend you on the exceptional work you've published and for making the repository available. It's been enlightening reviewing your code, and I have a few questions that I hope you could help clarify, particularly about the training code:
> 
> 1. As we can see, the GradCache technique is used for `GradCacheTrainer`. In the [code](https://github.com/ContextualAI/gritlm/blob/main/gritlm/training/gradcache_trainer.py#L584), there are six conditions including `self.split_emb`, `self.split_emb_full` and so on. I'm curious to understand whether the `else` clause is the only instance where GradCacheTrainer is utilized in the training process.
> 2. When using the GradCacheTrainer, is it necessary to define the `training_step` function as outlined in the [here](https://github.com/ContextualAI/gritlm/blob/main/gritlm/training/run.py#L385), or can this be omitted?
> 
> My answer to these questions is `yes` for both.

1. `else` is the only instance where GradCache is used.
2. Yes this is till necessary. The purpose of that function is to ensure that both gen & emb losses can be tracked in e.g. wandb.

**Comment by MikeDean2367** [comment]
Thank you for your response. Regarding the second question, under the premise of using `GradCacheTrainer`, I believe there is no need to define the `training_step` function in [run.py](https://github.com/ContextualAI/gritlm/blob/main/gritlm/training/run.py#L385). The reason is that line 704 of [gradcache_trainer.py](https://github.com/ContextualAI/gritlm/blob/main/gritlm/training/gradcache_trainer.py#704) has already logged different losses. Therefore, I think that when using `GradCacheTrainer`, it is not necessary to define a `training_step` because it will not be called.

**Comment by Muennighoff** [comment]
> Thank you for your response. Regarding the second question, under the premise of using `GradCacheTrainer`, I believe there is no need to define the `training_step` function in [run.py](https://github.com/ContextualAI/gritlm/blob/main/gritlm/training/run.py#L385). The reason is that line 704 of [gradcache_trainer.py](https://github.com/ContextualAI/gritlm/blob/main/gritlm/training/gradcache_trainer.py#L704) has already logged different losses. Therefore, I think that when using `GradCacheTrainer`, it is not necessary to define a `training_step` because it will not be called.

Ah yeah you're right, sorry. The training_step is never used for the GradCacheTrainer cuz it's commented out here https://github.com/ContextualAI/gritlm/blob/09d8630f0c95ac6a456354bcb6f964d7b9b6a609/gritlm/training/gradcache_trainer.py#L545 and done via the code you pointed to

**Comment by MikeDean2367** [comment]
Thank you for your reply :)

**Comment by MikeDean2367** [comment]
Thank you for your reply!
