### ISSUE TITLE
model before fine-tuning issue

### ISSUE THREAD

**Issue by BlackHandsomeLee** [ContextualAI/gritlm#12]
Hello author, I want to reproduce your paper. Is it okay to use Mistral-7B-Instruct-v0.2 for the model before fine-tuning?

**Comment by BlackHandsomeLee** [comment]
or maybe mistralai/Mistral-7B-v0.1  can be used too？

**Comment by Muennighoff** [comment]
Yeah you can do that but note that we used https://huggingface.co/mistralai/Mistral-7B-v0.1
If you use the Instruct ones you may want to change the chat format in the code to continue using theirs

**Comment by BlackHandsomeLee** [comment]
> Yeah you can do that but note that we used https://huggingface.co/mistralai/Mistral-7B-v0.1 If you use the Instruct ones you may want to change the chat format in the code to continue using theirs

thank your for reply
