### ISSUE TITLE
Have you set negatives_cross_device=True in GRITLM-7B？

### ISSUE THREAD

**Issue by DreamInvoker** [ContextualAI/gritlm#23]
I notice that you write in-batch negatives loss in your paper, but the demo script for embedding-only training do not contain negatives_cross_device this parameter, Have you set negatives_cross_device=True for the best result in GRITLM-7B？

**Comment by Muennighoff** [comment]
The GritLM-7B training script is here: https://github.com/ContextualAI/gritlm/blob/main/scripts/training/train_gritlm_7b.sh

As you can see it is set to True.

**Comment by DreamInvoker** [comment]
Thank you !
