### ISSUE TITLE
sampling in-batch negatives

### ISSUE THREAD

**Issue by raghavlite** [ContextualAI/gritlm#30]
In the paper, you mention that you sample in batch examples from the same dataset. In training/run.py, you are concatenating all datasets [here](https://github.com/ContextualAI/gritlm/blob/a122855d6578a4f0980ea20340d5c9e1dd59d8c4/gritlm/training/run.py#L183). 

Is there any other location in the code where you specify to sample in batch negatives from the same dataset?

**Comment by Muennighoff** [comment]
Note that the lenghts of each dataset are saved right above.

They are then used to do the sampling in this class: 
https://github.com/ContextualAI/gritlm/blob/a122855d6578a4f0980ea20340d5c9e1dd59d8c4/gritlm/training/data.py#L284

**Comment by raghavlite** [comment]
thanks
