### ISSUE TITLE
About training data of embedding

### ISSUE THREAD

**Issue by zillion-zhao** [ContextualAI/gritlm#38]
Hello. I see that in the toy_data of embedding, each query have several negative samples, while when I download MEDI2 (parquet), each query has only one negative sample. I want to know which setting is used for training? The MEDI2.parquet can be directly used for training, or I should take additional actions?

**Comment by Muennighoff** [comment]
We use only one hard negative during training. This is controlled via `--train_group_size 2` where if it is `2` then only 1 hard negative will be chosen. You can directly use it for training.

**Comment by zillion-zhao** [comment]
OK, I just notice this option. Thank you for your kind reply.
