### ISSUE TITLE
Question about in-batch negatives in the training loop.

### ISSUE THREAD

**Issue by DreamInvoker** [ContextualAI/gritlm#44]
https://github.com/ContextualAI/gritlm/blob/58ccad88e34e133f6a9680d9ce44854ad26a8c7c/gritlm/training/arguments.py#L46-L54

"Besides the negatives in this group, the in-batch negatives will also be used in fine-tuning."

I use this [file](https://github.com/ContextualAI/gritlm/blob/main/gritlm/training/toy_data_instruct/toy_data_embedding.jsonl) as train data, where each query has 1 positives and 7 negatives. When I set train_group_size=2 and per_device_train_batch_size=**2**, do I use the negatives in the mini-batch of two samples per step?  When I set train_group_size=2 and per_device_train_batch_size=**1**, do I use the negatives in the mini-batch of one sample per step? 

I am confused about the negatives provided in the file and in-batch. 

And where is the code logic of in-batch negative sampling?

**Comment by Muennighoff** [comment]
in-batch negatives are using the other samples in the same batch as negatives. It happens in https://github.com/ContextualAI/gritlm/blob/0cc9aeab83b90f2e22bcdd2b084d51507c624d95/gritlm/training/model.py#L36

they are gathered across devices thus it depends on your global batch size how many in-batch negatives there are.

the regular negatives (or hard negatives) meanwhile do not depend on batch size and just on `train_group_size`

**Comment by DreamInvoker** [comment]
Totaly understood! Thanks!
