### ISSUE TITLE
Full Finetuning or LoRA ?

### ISSUE THREAD

**Issue by hjq133** [ContextualAI/gritlm#5]
Great job! 
One question: Are you using full finetuning throughout the entire process? Have you tried LoRA's performance?

I remember in the previous work (https://arxiv.org/pdf/2401.00368.pdf), which also using LLM as embedder, they use LoRA and still get good performance.

**Comment by Muennighoff** [comment]
We do full-finetuning and did not try LoRA, but I think it should work! Let us know if you try it :)
