### ISSUE TITLE
LORA + FSDP

### ISSUE THREAD

**Issue by spookyQubit** [ContextualAI/gritlm#68]
Hi @Muennighoff , 

Thanks a lot for making the code public. Was wondering if you have tried training with `LORA` using `FSDP`? 

I have been trying to get this to work, but I am running into issues (which is compounded by the fact that there are so many parameters to pay attention to in the `accelerate` config, for example `use_orig_params`, `fsdp_auto_wrap_policy` and so on and also the exact mechanism to save/load the model checkpoints). Any pointers that you may have (from this project or otherwise), would be greatly appreciated. 

Thanks,
Shantanu

**Comment by Muennighoff** [comment]
I havn't tried LoRA but it should be relatively easy to get to work. I recommend debugging with a small model.

**Comment by spookyQubit** [comment]
Thanks @Muennighoff  :)
