### ISSUE TITLE
eager vs. flash vs. sdpa

### ISSUE THREAD

**Issue by hjq133** [ContextualAI/gritlm#9]
Slid work ! 

Have you ever compared the differences between flash attention, sdpa, and eager attention? I used GRITLM to test these three attentions implementation during finetune and found that their speed and memory usage are almost the same.
Are you the same?

Thanks !

**Comment by Muennighoff** [comment]
Yeah, we found that SDPA with the latest torch version is the best for both speed & memory. It uses FA2.
